pull out git commands into config

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -3,34 +3,34 @@ if command -v realpath >/dev/null 2>&1; then
     SCRIPTS="$(dirname $(realpath "${BASH_SOURCE[0]}" 2>/dev/null))"
 elif command -v readlink >/dev/null 2>&1 \
     && readlink --canonicalize-existing ~ >/dev/null 2>&1; then
-    SCRIPTS="$(dirname $(readlink --canonicalize-existing ${BASH_SOURCE[0]}))"
+    SCRIPTS="$(dirname $(readlink --canonicalize-existing "${BASH_SOURCE[0]}"))"
 elif command -v readlink >/dev/null 2>&1; then
-    SCRIPTS="$(dirname $(readlink ${BASH_SOURCE[0]}) 2>/dev/null)"
+    SCRIPTS="$(dirname $(readlink "${BASH_SOURCE[0]}") 2>/dev/null)"
 fi
 
-if [ "$SCRIPTS" == "" ] || [ "$SCRIPTS" == "${HOME}" ]; then
+if [ "${SCRIPTS}" == "" ] || [ "${SCRIPTS}" == "${HOME}" ]; then
     SCRIPTS=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)
-    if [ "$SCRIPTS" == "${HOME}" ]; then echo "Where am I"; fi
+    if [ "${SCRIPTS}" == "${HOME}" ]; then echo "Where am I"; fi
 fi
-pathadd() { [[ ":$PATH:" != *":$1:"* ]] && export PATH="${PATH:+"$PATH:"}$1"; }
-pathaddfirst() { [[ ":$PATH:" != *":$1:"* ]] && export PATH="$1${PATH:+":$PATH"}"; }
-pathadd "$SCRIPTS"
-DOT="$(cd $SCRIPTS/..; pwd -P)"
+pathadd() { [[ ":${PATH}:" != *":$1:"* ]] && export PATH="${PATH:+"${PATH}:"}$1"; }
+pathaddfirst() { [[ ":${PATH}:" != *":$1:"* ]] && export PATH="$1${PATH:+":${PATH}"}"; }
+pathadd "${SCRIPTS}"
+DOT="$(cd "${SCRIPTS}"/.. || exit; pwd -P)"
 DOT_DEST=~/local/dot
 LOCALDOT=~/.local-dot
 
 error() {
     RED='\033[0;31m'
     NC='\033[0m' # No Color
-    echo -e ${RED}${@}${NC}
+    echo -e "${RED}"${@}"${NC}"
 }
 
 run-quiet() {
     title="$1"
     shift
-    echo -n $title...
+    echo -n "${title}"...
     err=$( { $@ >/dev/null; } 2>&1) && echo ok || error error
-    [ "$err" ] && error "$err"
+    [ -n "${err}" ] && error "${err}"
 }
 
 me() {
@@ -45,22 +45,22 @@ me() {
 go() {
     [ "$1" == "--no" ] && local no="--no" || local no=""
 
-    mkdir -p $LOCALDOT/{status,conf,commands}
+    mkdir -p ${LOCALDOT}/{status,conf,commands}
     mkdir -p ~/.tmp
 
-    [ "$no" ] || setup-me
+    [ -n "${no}" ] || setup-me
 
     setup-dirs-simple
-    hash -r; pathaddfirst $SCRIPTS
+    hash -r; pathaddfirst "${SCRIPTS}"
 
-    setup-install $no
+    setup-install ${no}
 
     setup-dot
     build cron install ~/.cron
 
     build system is-mac && setup-osx
 
-    if [ "$no" == "" ]; then
+    if [ "${no}" == "" ]; then
         setup-git
     else
         echo "run setup git"
@@ -69,68 +69,78 @@ go() {
 
 setup-osx() {
     build mac dud mail
-    bash $DOT/conf/osx;
+    bash "${DOT}"/conf/osx;
 }
 
 setup-me() {
     read -p "make home?[Y/n]" q
-    if [ "$q" == "" ]; then touch $LOCALDOT/status/home.me;
-    else rm -f $LOCALDOT/status/home.me; fi
+    if [ "${q}" == "" ]; then touch ${LOCALDOT}/status/home.me;
+    else rm -f ${LOCALDOT}/status/home.me; fi
 }
 
 setup-dot() {
     # build symc clean ~/
-    build symc link-dir $DOT/conf ~/.
+    build symc link-dir "${DOT}"/conf ~/.
     . ~/.bashrc
 }
 
 setup-dirs-simple() {
-    mkdir -p "$DOT_DEST"
-    if [ "$DOT_DEST" != "$DOT" ]; then
-        build symc safe-cp "$DOT" "$DOT_DEST"
-        DOT="$DOT_DEST"
-        SCRIPTS="$DOT/bin"
+    mkdir -p "${DOT_DEST}"
+    if [ "${DOT_DEST}" != "${DOT}" ]; then
+        build symc safe-cp "${DOT}" "${DOT_DEST}"
+        DOT="${DOT_DEST}"
+        SCRIPTS="${DOT}/bin"
     fi
 }
 
 setup-install() {
-    build install restore $DOT/install
+    build install restore ${DOT}/install
     echo "The following extras must be installed on their own"
     echo 'peppermint'
     if [ "$1" != "--no" ] && [ "$1" != "no" ]; then
         read -p "Run Setups? [yes] " r
-        if [ "$r" == "" ]; then
-            open $DOT/conf/taylormint.terminal
+        if [ "${r}" == "" ]; then
+            open ${DOT}/conf/taylormint.terminal
         fi
     fi
 }
 
+git-prompt() {
+    field="$1"
+    default="$2"
+    default_prompt=""
+    [ "${default}" != "" ] && default_prompt=" [${default}]"
+    read -p "${field}${default_prompt}: " value
+    if [ "${value}" == "" ]; then value="${default}"; fi
+    if [ "${value}" == "" ]; then return; fi
+    config="${LOCALDOT}/conf/config.git"
+    git config --file="${config}" "${field}" "${value}"
+}
+
 setup-git() {
-    default_email=git@taylorlmoney.com
-    read -p "git email [$default_email]: " email
-    if [ "$email" == "" ]; then email="$default_email"; fi
-    build template fill --email "$email" $DOT/templates/git.bash.template > $LOCALDOT/conf/git.bash
-    . $LOCALDOT/conf/git.bash
+    git-prompt user.email git@taylorlmoney.com
+    git-prompt github.user
+    git-prompt github.token
 }
 
 
 a="$1"
 shift;
-if [ "$a" == "git" ]; then
+if [ "${a}" == "git" ]; then
     setup-git "$@"
-elif [ "$a" == "dot" ]; then
+elif [ "${a}" == "dot" ]; then
     setup-dot "$@"
-elif [ "$a" == "osx" ]; then
+elif [ "${a}" == "osx" ]; then
     setup-osx "$@"
-elif [ "$a" == "go" ]; then
+elif [ "${a}" == "go" ]; then
     go "$@"
-elif [ "$a" == "all" ]; then
+elif [ "${a}" == "all" ]; then
     go "$@"
-elif [ "$a" == "no" ]; then
+elif [ "${a}" == "no" ]; then
     go --no "$@"
-elif [ "$a" == "me" ]; then
+elif [ "${a}" == "me" ]; then
     me "$@"
-elif [ "$a" == "install" ]; then
+elif [ "${a}" == "install" ]; then
     setup-install "$@"
 else
     echo "git: run git setup"
